### ISSUE TITLE
Returning type from scraper to bot input.

### ISSUE THREAD

**Issue by antof27** [antof27/xCoreBot#3]
Scraper is now working on local istances, emulating the command call through a string. The query (both /all and /filter) is now return a list of list. Each release is stored in the sublists containing its information ([genre, country, title, artist]). Considering you should call the a scraper function and obtaining data to show in the chat, what type of input are thinking to receive from the scraper?

**Comment by SalvoSamba01** [comment]
In the code I used a dictionary of lists, do I have to change it in your opinion?
