### ISSUE TITLE
"/filter" command logic

### ISSUE THREAD

**Issue by SalvoSamba01** [antof27/xCoreBot#5]
I'm currently working on the "/filter" command, but i have to decide the logic of combining filters.
Currently, I'm considering whether filters should be applied in a logical AND (if the user entered multiple filters, should they be satisfied all at once) or OR (if the user entered multiple filters, should they be satisfied at least one of them)
Any suggestion?

**Comment by antof27** [comment]
Nice question Salvo, the actual version of the scraper contains the AND logic between the filters, so the outcomes have to match every query value. It is a fine-grained search that would allow the user to retrieve more detailed matches. 
For instance: "/filter -gc alternative metal, Italy" should only match the alternative metal band from Italy. Implementing an OR logic would match both Italian releases and alternative metal releases that in my opinion go against the filter criterion.

**Comment by SalvoSamba01** [comment]
Ok i'll change that
