### ISSUE TITLE
Number in command is no longer total page number 

### ISSUE THREAD

**Issue by antof27** [antof27/xCoreBot#7]
Hi Salvo, 
I thought that the page number specified in the command is a more technical parameter that should not be exposed to the user. Therefore, I modified the code in a way that the last number in the command line now represents the amount of songs that the user want to look for. I managed the number of pages to scrape based on the fixed length number of releases in each page. 

Furthermore, a higher number of songs to scrape, will require more time to make the requests to the site. Considering that a page contains 32 elements and the time to perform a search on 1 page take at least 1 seconds, the required time to obtain a response from the scraper is about _ceiling((#songs/32)*1)_

For instance: /all 300 will scrape the firsts ceiling(300/32) = 10 pages, with 300 output songs and will require at least 10 seconds of executing time. Meanwhile, you could display some message in the chat such as "Searching your releases..." 

One last point, I specified a reverse order of the outcome list, in order to have the latest releases on the bottom of the chat. 

Note: The search always has a convergence, both with or without results.

**Comment by SalvoSamba01** [comment]
It sounds good. I'll change the meaning of "n" parameter in the Bot code
